rm -rf app/CalculatorGlobalStub
rm -rf app/CompassGlobalStub
rm -rf app/IdMipay
rm -rf app/InMipay
rm -rf app/Lens
rm -rf app/MSA-Global
rm -rf app/MiDropStub
rm -rf app/MiPicks
rm -rf app/MiuiBugReport
rm -rf app/MiuiVideoPlayer
rm -rf app/NotesGlobalStub
rm -rf app/PaymentService
rm -rf app/ScreenRecorderGlobalStub
rm -rf app/facebook-appmanager
rm -rf data-app/MiCreditInStub
rm -rf priv-app/Calendar
rm -rf priv-app/CleanMaster
rm -rf priv-app/MiBrowserGlobal
rm -rf priv-app/MiService
rm -rf priv-app/MiShare
rm -rf priv-app/MiuiBrowserGlobal
rm -rf priv-app/MiuiMusicGlobal
rm -rf priv-app/ScannerGlobalStub
rm -rf priv-app/SoundRecorderStub
rm -rf priv-app/YellowPage
rm -rf priv-app/facebook-installer
rm -rf priv-app/facebook-services
rm -rf product/app/Gmail2
rm -rf product/app/Maps
rm -rf product/app/YouTube
rm -rf product/priv-app/Velvet
rm -rf product/priv-app/Wellbeing