#System
echo "- System Debloating..."
rm -rf app/AnalyticsCore
rm -rf app/BluetoothMidiService
rm -rf app/CalculatorGlobalStub
rm -rf app/CatchLog
rm -rf app/CloudService
rm -rf app/CompassGlobalStub
rm -rf app/DebugLoggerUI
rm -rf app/FidoAuthen
rm -rf app/FidoClient
rm -rf app/GooglePrintRecommendationService
rm -rf app/HybridAccessory
rm -rf app/HybridPlatform
rm -rf app/InMipay
rm -rf app/Joyose
rm -rf app/Joyose/lib
rm -rf app/Lens
rm -rf app/LiveWallpapersPicker
rm -rf app/MSA-Global
rm -rf app/MiCloudSync
rm -rf app/MiDropStub
rm -rf app/MiPicks
rm -rf app/MiPlayClient
rm -rf app/MiuiAudioMonitor
rm -rf app/MiuiBugReport
rm -rf app/MiuiDaemon
rm -rf app/MiuiDaemon/lib
rm -rf app/MiuiFrequentPhrase
rm -rf app/MiuiVideoPlayer
rm -rf app/Netflix_activation
rm -rf app/NotesGlobalStub
rm -rf app/PartnerBookmarksProvider
rm -rf app/PaymentService
rm -rf app/PlayAutoInstallStubApp
rm -rf app/PrintSpooler
rm -rf app/PrintSpooler/lib
rm -rf app/SoterService
rm -rf app/SystemAppUpdater
rm -rf app/TouchAssistant
rm -rf app/Traceur
rm -rf app/UpnpService
rm -rf app/WMService
rm -rf app/WeatherGlobalStub
rm -rf app/XiaomiServiceFramework
rm -rf app/XiaomiSimActivateService
rm -rf app/XiaomiSimActivateService/lib
rm -rf app/facebook-appmanager
rm -rf app/mi_connect_service
rm -rf data-app/MiCreditInStub
rm -rf data-app/MiRadio
rm -rf etc/gboard_theme/xiaomi_theme_20171222.zip
rm -rf priv-app/Backup
rm -rf priv-app/BuiltInPrintService
rm -rf priv-app/BuiltInPrintService/lib
rm -rf priv-app/BuiltInPrintService/lib/arm64/libwfds.so
rm -rf priv-app/CellBroadcastServiceModulePlatform
rm -rf priv-app/CleanMaster
rm -rf priv-app/CloudBackup
rm -rf priv-app/CloudServiceSysbase
rm -rf priv-app/CtsShimPrivPrebuilt
#rm -rf priv-app/DownloadProviderUi
rm -rf priv-app/GlobalMinusScreenBase
rm -rf priv-app/MiBrowserGlobal
rm -rf priv-app/MiCalendarGlobal
rm -rf priv-app/MiService
rm -rf priv-app/MiShare
rm -rf priv-app/MiuiBrowserGlobal
rm -rf priv-app/MiuiMusicGlobal
rm -rf priv-app/ONS
rm -rf priv-app/SoundRecorderStub
rm -rf priv-app/Stk1
rm -rf priv-app/Tag
rm -rf priv-app/WapiCertManager
rm -rf priv-app/WapiCertManager/lib
rm -rf priv-app/WapiCertManager/lib/arm64
rm -rf priv-app/YellowPage
rm -rf priv-app/facebook-installer
rm -rf priv-app/facebook-services
rm -rf product/app/Chrome
rm -rf product/app/Gmail2
rm -rf product/app/GoogleTTS
rm -rf product/app/Maps
rm -rf product/app/YouTube
rm -rf product/app/talkback
rm -rf product/etc/sysconfig/wellbeing.xml
rm -rf product/overlay/AccentColorBlack
rm -rf product/overlay/AccentColorCinnamon
rm -rf product/overlay/AccentColorGreen
rm -rf product/overlay/AccentColorOcean
rm -rf product/overlay/AccentColorOrchid
rm -rf product/overlay/AccentColorPurple
rm -rf product/overlay/AccentColorSpace
rm -rf product/overlay/IconPackCircularAndroid
rm -rf product/overlay/IconPackCircularLauncher
rm -rf product/overlay/IconPackCircularSettings
rm -rf product/overlay/IconPackCircularSystemUI
rm -rf product/overlay/IconPackCircularThemePicker
rm -rf product/overlay/IconPackFilledAndroid
rm -rf product/overlay/IconPackFilledLauncher
rm -rf product/overlay/IconPackFilledSettings
rm -rf product/overlay/IconPackFilledSystemUI
rm -rf product/overlay/IconPackFilledThemePicker
rm -rf product/overlay/IconPackRoundedAndroid
rm -rf product/overlay/IconPackRoundedLauncher
rm -rf product/overlay/IconPackRoundedSettings
rm -rf product/overlay/IconPackRoundedSystemUI
rm -rf product/overlay/IconPackRoundedThemePicker
rm -rf product/overlay/IconShapePebble
rm -rf product/overlay/IconShapeRoundedRect
rm -rf product/overlay/IconShapeSquircle
rm -rf product/overlay/IconShapeTaperedRect
rm -rf product/overlay/IconShapeTeardrop
rm -rf product/overlay/IconShapeVessel
rm -rf product/overlay/NavigationBarMode3Button
rm -rf product/overlay/NavigationBarModeGestural
rm -rf product/overlay/NavigationBarModeGesturalExtraWideBack
rm -rf product/overlay/NavigationBarModeGesturalNarrowBack
rm -rf product/overlay/NavigationBarModeGesturalWideBack
rm -rf product/priv-app/AndroidAutoStub
rm -rf product/priv-app/HotwordEnrollmentOKGoogleCORTEXM4
rm -rf product/priv-app/HotwordEnrollmentXGoogleCORTEXM4
rm -rf product/priv-app/Turbo
rm -rf product/priv-app/Velvet
rm -rf product/priv-app/Wellbeing
rm -rf system_ext/app/FM
rm -rf system_ext/app/FM/lib
rm -rf system_ext/app/FM/lib/arm64/libmp3lame.so
rm -rf system_ext/priv-app/CellBroadcastAppPlatform
rm -rf system_ext/priv-app/EmergencyInfo
rm -rf system_ext/priv-app/GoogleFeedback
rm -rf system_ext/priv-app/Omacp
sleep 5

echo "- Debloat operations completed..."
echo "       By @the_CEHunter       "